### PR TITLE
Run travis with ghc-8.0.1

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
`should-not-typecheck` doesn't seem to work with `ghc-8.0.1`. And I don't see any solution to fix it.

**Comment by kosmikus** [comment]
@phadej The code should check for `TypeError` rather than `ErrorCall` for ghc-8.0.1, as deferred type errors now have their own dedicated exception type.

**Comment by CRogers** [comment]
Awesome, thanks. I'll take a look when I get home tonight (alternately a PR would be great :p).

**Comment by phadej** [comment]
@kosmikus @CRogers If I change `ErrorCall` to `TypeError` the issue doesn't go away. Seems that `should-not-typecheck` block cannot catch the exception anymore:

```
parallels@ubuntu:~/mess/should-not-typecheck$ git diff
diff --git a/src/Test/ShouldNotTypecheck.hs b/src/Test/ShouldNotTypecheck.hs
index fd85ec0..b0a54b4 100644
--- a/src/Test/ShouldNotTypecheck.hs
+++ b/src/Test/ShouldNotTypecheck.hs
@@ -1,7 +1,7 @@
 module Test.ShouldNotTypecheck (shouldNotTypecheck) where

 import Control.DeepSeq (force, NFData)
-import Control.Exception (evaluate, try, throwIO, ErrorCall(..))
+import Control.Exception (evaluate, try, throwIO, ErrorCall(..), TypeError(..))
 import Data.List (isSuffixOf)
 import Test.HUnit.Lang (Assertion, assertFailure)

@@ -24,7 +24,7 @@ shouldNotTypecheck a = do
   result <- try (evaluate $ force a)
   case result of
     Right _ -> assertFailure "Expected expression to not compile but it did compile"
-    Left (ErrorCall msg) -> case isSuffixOf "(deferred type error)" msg of
+    Left (TypeError msg) -> case isSuffixOf "(deferred type error)" msg of
       True -> case isSubsequenceOf "No instance for" msg && isSubsequenceOf "NFData" msg of
         True -> assertFailure $ "Make sure the expression has an NFData instance! See docs at https://github.com/CRogers/should-not-typecheck#nfdata-a-constraint. Full
         False -> return ()
parallels@ubuntu:~/mess/should-not-typecheck$ cabal test
Preprocessing library should-not-typecheck-2.0.1...
Preprocessing test suite 'tests' for should-not-typecheck-2.0.1...
Running 1 test suites...
Test suite tests: RUNNING...
tests: test/ShouldNotTypecheckSpec.hs:82:32: error:
    • Couldn't match type ‘Bool’ with ‘Int’
      Expected type: Expr Int
        Actual type: Expr Bool
    • In the first argument of ‘Add’, namely ‘(BoolVal True)’
      In the first argument of ‘shouldNotTypecheck’, namely
        ‘(Add (BoolVal True) (IntVal 4))’
      In a stmt of a 'do' block:
        shouldNotTypecheck (Add (BoolVal True) (IntVal 4))
(deferred type error)
Test suite tests: FAIL
Test suite logged to: dist/test/should-not-typecheck-2.0.1-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

I also tried to modify `shouldNotTypecheck` to

``` hs
shouldNotTypecheck _ = return ()
```

and the `TypeError` is still thrown, I'm not sure what happens, but seems like exception is thrown in outer scope already. And I'm not sure whether that is a GHC bug?

I tried to come with smaller example in `ghci`

### GHC 7.10.3

```
Prelude> let foo _ = return () >> putStrLn "OK"
Prelude> let x = foo (True :: Int)

<interactive>:16:14: Warning:
    Couldn't match expected type ‘Int’ with actual type ‘Bool’
    In the first argument of ‘foo’, namely ‘(True :: Int)’
    In the expression: foo (True :: Int)
Prelude> x
OK
```

### GHC 8.0.1

```
parallels@ubuntu:~/mess$ ghci
GHCi, version 8.0.0.20160316: http://www.haskell.org/ghc/  :? for help
Prelude> let foo _ = return () >> putStrLn "OK"
Prelude> let x = foo (True :: Int)

<interactive>:2:14: error:
    • Couldn't match expected type ‘Int’ with actual type ‘Bool’
    • In the first argument of ‘foo’, namely ‘(True :: Int)’
      In the expression: foo (True :: Int)
      In an equation for ‘x’: x = foo (True :: Int)
```

N.B. an error, not a warning as with 7.10.3!

**Comment by thoughtpolice** [comment]
This looks like a manifestation of [GHC Ticket #11197](https://ghc.haskell.org/trac/ghc/ticket/11197), FWIW.

**Comment by phadej** [comment]
I see that milestone is marked for `8.0.2`, @kosmikus should we disable `should-not-typecheck` tests for GHC-8.0.1 in servant?

@CRogers, I'd also make revisions to `should-not-typecheck`, so it's not buildable with `ghc-8.0.1` (restrict base). And I guess we don't have other solution than wait for 8.0.2?

**Comment by kosmikus** [comment]
@phadej I'm not 100% convinced this cannot be worked around in 8.0.1 somehow. I had made some local tests and did get the expected results (but with code not completely equivalent to the stuff in should-not-typecheck). But yes, if there's no easy way, I'd go for disabling the tests temporarily, in the hope this will ultimately work again.

**Comment by goldfirere** [comment]
I have a workaround.

Yes, this is GHC #11197. The problem is that GHC 8 is not very clever when figuring out where, precisely, to put the deferred type error in the compiled program (that is, how deep evaluation needs to get before triggering the runtime error), and it often puts it way too early. The way to fix this is to tell GHC precisely where to put it, which will be at the largest enclosing contexts that mucks with constraints. To get GHC to make the right context, you just need a higher-rank type. This worked for me:

```
shouldNotTypecheck :: NFData a => (() ~ () => a) -> Assertion
```

Now, GHC knows to put the deferred type error in the argument to `shouldNotTypecheck`, not on the line containing the call to `shouldNotTypecheck`. Running the testsuite showed failures, but I think @kosmikus addressed that above. It was a big improvement from the original state, where the testsuite didn't run at all.

It's terribly ugly that this type has to leak out to users reading Haddock, but it makes this package usable on GHC 8.

**Comment by phadej** [comment]
Thanks @goldfirere, it seems to work!

**Comment by kosmikus** [comment]
Yes, thanks @goldfirere.

**Comment by CRogers** [comment]
Great conversation! It's unfortunate to have to change the API for this workaround, I wonder if keeping `shouldNotTypecheck :: NFData a => a -> Assertion` but having it simply call to another package only function `shouldNotTypecheckWithWorkaround :: NFData a => (() ~ () => a) -> Assertion` would work. I need to set up the 8.0.1 rc3 before I can test this...

**Comment by CRogers** [comment]
Nope, that doesn't work. Great sadness. I see the CPP will not change the API for people not <8.0.0, so I'm happy to merge this in and do a release.

**Comment by CRogers** [comment]
Released: https://hackage.haskell.org/package/should-not-typecheck-2.1.0

**Comment by phadej** [comment]
Hackage trustee nitpick:

The major bump was really unnecessary, this is not breaking change, actually there are no new functionality at all, so it could have been `2.0.2` or `2.0.1.1`.

> All packages on Hackage **should** use PVP

**Comment by kosmikus** [comment]
@phadej The way the PVP is phrased it doesn't ever forbid you to make a major version bump. It gives conditions under which you must bump the major or minor version counter and when they may stay the same. (FWIW, I still agree with you. It seems it was unnecessary here. But if the PVP is supposed to be interpreted in the way that unnecessary version bumps are not ok, then it has to be changed.)

**Comment by CRogers** [comment]
Oh, I was not aware of this PVP, I was going by SemVer http://semver.org,
so this was not a major version bump in my mind.

**Comment by phadej** [comment]
It's on the [Hackage mainpage](http://hackage.haskell.org/). 

> Guidelines for Hackage Packages:
> - All packages should follow the [Package Versioning Policy (PVP)](https://wiki.haskell.org/Package_versioning_policy).
> - Packages cannot be deleted, so you should consider uploading new versions packages as a package candidate and testing before publishing it to the main index.

---

But don't worry, nothing bad happened. It's only a bit inconvenient for other people, who expect package version to follow PVP. Luckily it's trivial to transfer from SemVer to PVP. And if you make new packages, please use PVP right from the beginning.

**Comment by kosmikus** [comment]
@phadej But as I said, there was no violation of PVP here. The way you interpret it does not match the way it is phrased. If you want to change that, then you should change the PVP.

**Comment by phadej** [comment]
@kosmikus, sorry, I didn't meant that there was a PVP violation. I was surprised about the major bump, and suspected (right!) that PVP isn't known.

**Pull request merged**
